# Backup Status

STATUS_PENDING = "PENDING"
STATUS_RUNNING = "RUNNING"
STATUS_SUCCESS = "SUCCESS"
STATUS_FAILED = "FAILED"


# Backup Modules

FILES = "FILES"
REGISTRY = "REGISTRY"
SQL_BACKUP = "SQL BACKUP"
COMPRESSION = "COMPRESSION"
REMOTE_STORAGE = "REMOTE STORAGE"